#!/bin/bash

. "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/../env"

dump_file="$DUMP_PATH/$(basename "$0")"

mkdir -p "$DUMP_PATH"
rm -f "$dump_file"

for i in {0..126}; do
    ranstr -l 20000 -r a-d >> "$dump_file"
done

res="$(time (cat "$dump_file" | "$LCSS_BIN"))"

echo "$res" | while read rec; do
    expected_count="$(echo "$rec" | awk '{ print $1 }')"
    str="$(echo "$rec" | awk '{ print $2 }')"

    if [ -n "$str" ]; then
        if [ $(grep -c "$str" "$dump_file") -eq $expected_count ]; then
            echo "'$str' found in exactly $expected_count string(s)"
        else
            echo "Found mismatch with '$str'!" >&2
            exit 1
        fi
    fi
done
