#!/bin/bash

. "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/../env" --make

dump_file="$DUMP_PATH/$(basename "$0")"

mkdir -p "$DUMP_PATH"
rm -f "$dump_file"

for i in {0..126}; do
    ranstr -l 20000 -r a-d >> "$dump_file"
done

results="$(time (cat "$dump_file" | "$LCSS_BIN"))"

echo "$results" | while read record; do
    set $record
    expected_count="$1"
    sub="$2"

    if [ -n "$sub" ]; then
        if [ "$(grep -c "$sub" "$dump_file")" -eq "$expected_count" ]; then
            echo "'$sub' found in exactly $expected_count string(s)"
        else
            echo "Found mismatch with '$sub'!" >&2
            exit 1
        fi
    fi
done
