#!/bin/bash

self_path="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
test_path="$self_path/test"
test_file="$test_path/strings"
exe="$self_path/build/lcss"

mkdir -p "$test_path"
rm -f "$test_file"

for i in {0..125}; do
    ./ranstr -l 20000 -r a-d >> "$test_file"
done

make

cat "$test_file" |
"$exe" |
while read rec; do
    str="$(echo "$rec" | awk '{ print $2 }')"

    if [ -n "$str" ]; then
        expected_count="$(echo "$rec" | awk '{ print $1 }')"

        if [ $(grep -c "$str" "$test_file") -eq $expected_count ]; then
            echo "'$str' found $expected_count times"
        else
            echo "Found mismatch with '$str'"
            exit 1
        fi
    fi
done
