#!/bin/bash

. "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/env" --

if [ ! -d "$1" ]; then
    echo "$(basename $0) /path/to/fasta/dir"
    exit 1
fi

#
#dump_file="$DUMP_DIR/$(basename "$0")"
#
#script -q -c "$BASE_DIR/main \"$1\"" "$dump_file"
#

$BASE_DIR/main "$1" | less -R
