#!/bin/bash

if [ -z "$1" ] || [ -z "$2" ]; then
    echo "$(basename $0) /path/to/fasta/files out-file"
    exit 1
fi

for file in "$1"/*; do
    sed '1d' "$file" | tr -d [:space:] >> "$2"
    printf "\n" >> "$2"
done
