#!/bin/bash

self_path="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
src_path="$self_path/src"
build_path="$self_path/build"

mkdir -p build

(cd "$src_path" && gcc -O3 *.c -o "$build_path/lcs")

str=""

for i in {0..10}; do
    str="$str$(ranstr -l 1000 -r a-d)\n"
done

time (printf "$str" | "$build_path/lcs")
