#!/bin/bash

self_path="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
str_file="$self_path/ran_strings"
exe="$self_path/build/lcss"

str=""

for i in {0..126}; do
    str="$str$(ranstr -l 20000 -r a-d)\n"
done

make

time (printf "$str" | "$exe")
