#!/bin/bash

self_path="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "$self_path"

mkdir -p build

gcc -O3 *.c -o build/lcs

str=""

for i in {0..10}; do
    str="$str$(ranstr -l 1000 -r a-d)\n"
done

time (printf "$str" | ./build/lcs)
