#!/bin/bash

self_path="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
test_path="$self_path/test"
str_file="$test_path/$(basename "$0")"
lcss="$self_path/build/lcss"

mkdir -p "$test_path"
rm -f "$str_file"

for i in {0..126}; do
    ./ranstr -l 2000 -r a-d >> "$str_file"
done

make

time (cat "$str_file" | "$lcss")
