#!/bin/bash

self_path="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
test_path="$self_path/test"
str_file="$test_path/$(basename "$0")"
lcss="$self_path/build/lcss"

mkdir -p "$test_path"
rm -f "$str_file"

for i in {0..126}; do
    ./ranstr -l 20000 -r a-d >> "$str_file"
done

make

res="$(time (cat "$str_file" | "$lcss"))"

echo "$res" | while read rec; do
    expected_count="$(echo "$rec" | awk '{ print $1 }')"
    str="$(echo "$rec" | awk '{ print $2 }')"

    if [ -n "$str" ]; then
        if [ $(grep -c "$str" "$str_file") -eq $expected_count ]; then
            echo "'$str' found in exactly $expected_count string(s)"
        else
            echo "Found mismatch with '$str'!" >&2
            exit 1
        fi
    fi
done
