#!/bin/bash

. "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/../env" --

if [ -z "$1" ] || [ -n "$2" ] && [ ! -f "$2" ]; then
    echo "$(basename $0) substr [str_file]"
    exit 1
fi

str_file="${2:-/dev/stdin}"
substr="$1"
substr_len="$(printf "$substr" | wc -m)"

while read string; do
    len_from_start="$(printf "$string" | grep -o "^.*$substr" | wc -m)"
    len_to_end="$(printf "$string" | grep -o "$substr.*\$" | wc -m)"

    if [ "$len_from_start" -gt 0 ] && [ "$len_to_end" -gt 0 ]; then
        # -1 because `wc -m` counts the "\n" printed by `grep`
        echo "$((len_from_start - 1 - substr_len))" - "$((len_to_end - 1 - substr_len))"
    fi
done < "$str_file"
