#!/bin/bash

. "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/../env" --

if [ ! -f "$1" ] || [ -z "$2" ] || [ -z "$3" ]; then
    echo "$(basename $0) str_file seq1 seq2"
    exit 1
fi

str_file="$1"

seq1="$2"
seq2="$3"

len1="$(printf "$seq1" | wc -m)"
len2="$(printf "$seq2" | wc -m)"

distances=

while read line; do
    match1_len="$(printf "$line" | grep -o "$seq1.*$seq2" | wc -m)"
    match2_len="$(printf "$line" | grep -o "$seq2.*$seq1" | wc -m)"
    min_len="$(min "$match1_len" "$match2_len")"

    if [ "$min_len" -eq 0 ]; then
        min_len="$(max "$match1_len" "$match2_len")"
    fi

    if [ "$min_len" -eq 0 ]; then
        continue
    fi

    distances="$(printf "%s\n%s" "$((min_len - len1 - len2))" "$distances")"
done < "$str_file"

echo "$distances" | sort -n
