#!/bin/bash

. "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/../env" --

if [ -z "$1" ] || [ -z "$2" ] || [ -n "$3" ] && [ ! -f "$3" ]; then
    echo "$(basename $0) sub1 sub2 [str_file]"
    exit 1
fi

str_file="${3:-/dev/stdin}"
sub1="$1"
sub2="$2"

len1="$(printf "$sub1" | wc -m)"
len2="$(printf "$sub2" | wc -m)"

distances=

while read string; do
    match1_len="$(printf "$string" | grep -o "$sub1.*$sub2" | wc -m)"
    match2_len="$(printf "$string" | grep -o "$sub2.*$sub1" | wc -m)"
    min_len="$(min "$match1_len" "$match2_len")"

    if [ "$min_len" -eq 0 ]; then
        min_len="$(max "$match1_len" "$match2_len")"
    fi

    if [ "$min_len" -eq 0 ]; then
        continue
    fi

    distances="$(printf "%s\n%s" "$((min_len - len1 - len2))" "$distances")"
done < "$str_file"

echo "$distances" | sort -n
