#!/bin/bash

. "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/../env" --

max=2147483647

while [ $# -gt 0 ]; do
    case "$1" in
        -m|--min)
            min="$2"
            shift
            ;;
        -M|--max)
            max="$2"
            shift
            ;;
        *)
            echo "unrecognized argument '$1' in $(basename "$0")" 1>&2
            exit 1
            ;;
    esac

    shift
done

if ! is-int "$min" || ! is-int "$max"; then
    echo "$(basename $0) --min <m> --max <M>" 1>&2
    exit 1
fi

while read substr; do
    substr_len="$(printf "$substr" | wc -m)"

    if [ "$substr_len" -ge "$min" ] && [ "$substr_len" -le "$max" ]; then
        echo "$substr"
    fi
done
