#!/bin/bash

if [ -n "$1" ] && [ ! -f "$1" ]; then
    echo "$(basename $0) [str_file]"
    exit 1
fi

strings="$(cat "${1:-/dev/stdin}")"

echo "$strings" | while read str1; do
    echo "$strings" | while read str2; do
        if [ "$str1" != "$str2" ]; then
            echo "$str1 $str2"
            echo "$str2 $str1"
        fi
    done
done
