#!/bin/bash

if [ ! -f "$1" ]; then
    echo "$(basename $0) str_file [lcss-file]"
    exit 1
fi

str_file="$1"

declare -a lcss

while read line; do
    word_idx=0

    for word in ${line:2}; do
        echo "$word"
    done
done < "${2:-/dev/stdin}"
