#!/usr/bin/env python3

import sys

strings = []

for line in sys.stdin:
    line = line.strip()

    if line:
        strings.append(line)

def process_char(idx):
    char_set = set()

    for str in strings:
        try:
            char_set.add(str[idx])
        except IndexError:
            char_set.add(None)

    return char_set

max_len = 0

for str in strings:
    max_len = max(max_len, len(str))

in_tail = False

for idx in range(0, max_len):
    char_set = process_char(idx)

    if not in_tail and None in char_set:
        in_tail = True
        sys.stdout.write('(')

    char_set.discard(None)

    if len(char_set) == 1:
        sys.stdout.write(char_set.pop())
    else:
        sys.stdout.write('[%s]' % ''.join(sorted(char_set)))

if in_tail:
    sys.stdout.write(')?')

print()
