#!/bin/bash

. "$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)/mk-env" --

fasta_dir=
input_file=
min_common=0

while [ $# -gt 0 ]; do
    case "$1" in
        --min-common)
            min_common="$2"
            shift
            ;;
        --fasta-dir)
            fasta_dir="$2"
            shift
            ;;
        *)
            if [ -z "$input_file" ]; then
                input_file="$1"
            else
                echo "unrecognized argument '$1' in $(basename "$0")" 1>&2
                exit 1
            fi
            ;;
    esac

    shift
done

if [ ! -d "$fasta_dir" ]; then
    echo "$(basename "$0") --fasta-dir /path/to/fasta_dir"
    exit 1
fi

seq_with_names="$(normalize-fasta "$fasta_dir" --keep-names)"

while read record_lst; do
    idx=0
    record_count=

    for record in $record_lst; do
        if [ "$idx" -eq 0 ]; then
            record_count="$record"

            if [ "$record_count" -lt "$min_common" ]; then
                break
            fi
        else
            echo "$record_count $record"
            echo "$seq_with_names" | grep "$record" | awk -F '#' '{ print $1 }'
            echo
        fi

        idx="$((idx + 1))"
    done

done < "${input_file:-/dev/stdin}"
