#!/bin/bash

. "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/../env"

if [ -z "$1" ] || [ -z "$2" ] || [ -z "$3" ]; then
    echo "$(basename $0) str_file seq1 seq2"
    exit 1
fi

str_file="$1"

seq1="$2"
seq2="$3"

len1="$(strlength "$seq1")"
len2="$(strlength "$seq2")"

matches="$matches$(grep -o "$seq1.*$seq2" "$str_file")"
matches="$matches$(grep -o "$seq2.*$seq1" "$str_file")"

while read line; do
    count="$(echo "$line" | wc -m)"
    dist="$((count - len1 - len2))"

    distances="$(printf "%s\n%s" "$dist" "$distances")"
done <<< "$matches"

echo "$distances" | sort -n
